### ISSUE TITLE
bundle.js:784 ReferenceError: Autodesk is not defined

### ISSUE THREAD

**Issue by Mujtaba4ahmed** [Autodesk-Forge/forge-rcdb.nodejs#15]
I am getting this error on my browser console.
Also,
PS D:\W&W\forge-rcdb.nodejs-master> npm start

> forge-rcdb@4.0.0 start D:\W&W\forge-rcdb.nodejs-master
> node bin/start.js

Server listening on PORT: 3000
ENV: undefined
Connected to MongoDB Database: forge-rcdb
Cleaning Dir: D:\W&W\forge-rcdb.nodejs-master\TMP
Socket connected: I-a50mUi9DJcHk95AAAA
why do I see this ENV:undefined. The app is not running, just a blank page with autodesk error in the console.
Please respond asap.
Thanks.

**Comment by Yaxian** [comment]
try to modify [L12](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/package.json#L12) in `package.json` to

```
"start": "cross-env NODE_DEV=development HOT_RELOADING=true npm start"
```
or directly

```
./node_modules/.bin/cross-env  NODE_DEV=development HOT_RELOADING=true npm start
```

**Comment by Mujtaba4ahmed** [comment]
I will try that now.

Also, I am getting Autodesk is not defined in my browser console.
why do you think this is happening?
Please respond asap
thanks.

**Comment by Yaxian** [comment]
Maybe`viewer.js` loaded failed. You should ask @leefsmp for help.

**Comment by Mujtaba4ahmed** [comment]
Is viewer.js in the folder? He currently seems to be offline. how do I reach him?

**Comment by Yaxian** [comment]
maybe just wait.

**Comment by Mujtaba4ahmed** [comment]
I tried the solution you suggested. It is obviously going into loop.
calling npm start which inturn calls npm start is a loop.

**Comment by Yaxian** [comment]
sorry. I edited it.

**Comment by Mujtaba4ahmed** [comment]
I don't see any change.

**Comment by leefsmp** [comment]
I updated the config in the repo, should be ok for you now. Look [here](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/config/development.config.js#L60) for more details. The reason is that I'm using a local copy of the viewer3D.js but we are not allowed to push that to public repos due to MIT license, so you need to use the CDN version or download it locally yourself, if you want to run offline for example.

As for your initial issue, you need to make sure NODE_ENV variable is defined because it is what controls which config is being used: "${NODE_ENV}.config.js" where NODE_ENV can be "development" or "production".

Hope that helps.

**Comment by Mujtaba4ahmed** [comment]
I looked into it. I have a question that where should I download the viewer3D.js file for it run locally on my system.

Also, I am getting this error in the console:
Failed to load resource: the server responded with a status of 404 3000/resources/models/dev/engine/0.pf (Not Found) 

I looked into this path in my project and there is no resources/models/dev/ 'dev' folder in it.
Could you help me out with this?

**Comment by leefsmp** [comment]
You can download the viewer source from [extract.autodesk.io](https://extract.autodesk.io/).
