### ISSUE TITLE
click on "download  SVF" and has no any response

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#28]
hello, all, 

I am able to  upload and translate the  rvt file and also able to  navigate the model on the page successfully now.

but I can't download the SVF file, the browser has no any response when clicking

then F12, the browser say  " http://localhost:3000/api/extract/status/59e4a2a2d5098d332876b40c " 4.4 not found

![2017-10-16_21-02-51](https://user-images.githubusercontent.com/9555002/31613980-597a2658-b2b7-11e7-9af3-bb1d88f77e72.png)

what's wrong?

**Comment by leefsmp** [comment]
The 404 is expected as the .zip is not present on the server, however there is a problem with that specific file, try another file it should work. I can't tell you what the problem is, you would need to run the code on your side, take a look at this article: [Forge SVF Extractor in Node.js](https://forge.autodesk.com/blog/forge-svf-extractor-nodejs)

**Comment by leefsmp** [comment]
Same as [https://github.com/Autodesk-Forge/forge-rcdb.nodejs/issues/36](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/issues/36)
