### ISSUE TITLE
a certain model can't be downloaded , it model related?

### ISSUE THREAD

**Issue by ruixiwu** [Autodesk-Forge/forge-rcdb.nodejs#36]
hello, leefsmp

today, I can't download the villa model successfully shown as below.  I think this model is uploaded by me (not sure, I did upload a similar villa model several days ago).  maybe it contains some Chinese characters.
the other models seem OK to be downloaded.

![2017-11-02_10-24-30](https://user-images.githubusercontent.com/9555002/32306906-86d82330-bfb8-11e7-9e2e-c63f9871d743.png)

can you check that behavior? I did that in Edge and Chrome, and act the same.

ruixi

**Comment by ruixiwu** [comment]
once again,  another model can't be downloaded also, that model is uploaded by others I don't known, but it's Chinese model obviously.

**Comment by leefsmp** [comment]
The issue is probably due to Chinese characters in the name of some resources of the project. We do not officially support downloading resources associated with a Forge model, so not much I can do for you there. Take a look at this project which allows you to download a model translated with your own Forge credentials: [https://github.com/leefsmp/forge-extractor](https://github.com/leefsmp/forge-extractor).
