### ISSUE TITLE
error after setup

### ISSUE THREAD

**Issue by theextremeandy** [Autodesk-Forge/forge-rcdb.nodejs#39]
HI Phillipe,
I try to use your great work. 
The setup of the environment is really very very difficult.
I installed nodejs, gtk, python and mongodb.
After many errors and checks, npm start seems to be finally in place now 
but when I launch the browser I only see the error:
Can not GET /
I searched the string "Can not GET" by enabling the match case in the whole source without finding it.
Can you help me please?
andrea

**Comment by leefsmp** [comment]
It is a rather large sample, so it's not easy to keep it simple. On MacOS or Linux based OS the `npm install` is effortless ... You are getting this error most likely because you are running in dev mode without enabling hot reloading. Make sure the following env variables are defined as below:

NODE_ENV=development

HOT_RELOADING=true
 
If you run in production:

NODE_ENV=production

No need hot reloading in prod and the dist/ directory should build automatically at the first run, you may have to wait for a bit.

Hope that helps

**Comment by Yaxian** [comment]
#15
