### ISSUE TITLE
How to convert the current code to js

### ISSUE THREAD

**Issue by teren203** [Autodesk-Forge/forge-rcdb.nodejs#49]
Hi,
Since my current project uses .net mvc, how can I embed your code in my project? Can you turn your code into a simple js code?

**Comment by leefsmp** [comment]
Give me about a year to migrate the 70895 lines of code of this project and I will get back to you ...

<img width="336" alt="screen shot 2018-05-08 at 06 50 28" src="https://user-images.githubusercontent.com/4352502/39738582-475dc6b2-528c-11e8-87e7-dd03b439908b.png">

**Comment by leefsmp** [comment]
Give me about a year to migrate the 70895 lines of code of this project and I will get back to you ...

<img width="336" alt="screen shot 2018-05-08 at 06 52 38" src="https://user-images.githubusercontent.com/4352502/39738622-826a1238-528c-11e8-8581-d59a6002a5b0.png">

**Comment by teren203** [comment]
Sorry about that stupid question, then I have another problem. When I copy the contents of your ./resource/prod/gallery.models.json to the mongo table, the prompt is wrong. How can I solve this? Thank you.
![tim 20180508135105](https://user-images.githubusercontent.com/29408498/39740194-2453f0e8-52c7-11e8-8fdb-aa59a132f839.png)
![tim 20180508135154](https://user-images.githubusercontent.com/29408498/39740202-31041d72-52c7-11e8-8eb3-c01f9727e442.png)

**Comment by leefsmp** [comment]
This could be a problem with the tool you are using to import the json. The export was done using [Studio3T](https://studio3t.com), you should be able to do the same if you use this tool. Otherwise you could remove the `timestamp` entry. 

You shouldn't be importing the prod models anyway because those have been translated with my set of Forge credentials, you will not be able to load them in the viewer when using your keys anyway.

What you should do is run the sample in `development` mode and use the `/gallery` section to import your own models. You can also run in `production` mode but take a look at the [config](https://github.com/Autodesk-Forge/forge-rcdb.nodejs/blob/master/config/production.config.js) and modify it accordingly.

About the js code, no it's not possible to migrate all of it in a reasonable amount of time, a better approach would be to learn on your side how to setup babel+webpack for your asp.net project, so you could easily reuse it. The time you spend learning this will greatly improve your web development experience in the future. The project contains lot of separate demos, I would be surprised if you need all of them in your project, you may just want to migrate a few or look how it's working then implement your own solution more suitable to your environment.

Keep in mind this is not a "getting started" project, so it has not been designed to grab some code and run it on a different project, some extensions are using dependencies in the project so it may require to be a bit familiar with the whole code in order to extract some of them, unfortunately.

**Comment by teren203** [comment]
thanks for your help
