### ISSUE TITLE
Why can't the model load?

### ISSUE THREAD

**Issue by qiuyuehuang** [Autodesk-Forge/forge-rcdb.nodejs#52]
Why do I have this situation after running?
![image](https://user-images.githubusercontent.com/38748038/44951607-dfef5200-ae9a-11e8-8ef3-ab7e1a0f83c2.png)
Can you help me?thanks

**Comment by kingov** [comment]
the same question

**Comment by leefsmp** [comment]
Database not populated.. where do you think the server will find the models from?

**Comment by PavelBalobanov** [comment]
> Database not populated.. where do you think the server will find the models from?

Hello! Many thanks for the samples you provided!

Let me know, please, how to fill the Database?

**Comment by libvarun** [comment]
Install https://studio3t.com/download/
and add collections given in https://github.com/Autodesk-Forge/forge-rcdb.nodejs/tree/master/resources/db/dev

**Comment by marty3747** [comment]
@libvarun 
Good day! I came across a completely similar problem that is described in this question. Could you explain how to add collections after installing studio 3t, so that the models on localhost 3000 become visible? I have already installed the mongoDB database, but at the moment I don’t quite understand my next steps for adding collections. The screenshot shows what I have at the moment Thanks. 
![image](https://user-images.githubusercontent.com/52569199/63154077-8daa3100-c018-11e9-88f3-a61ea09603ff.png)
